---
- name: "[dependencies] | Install python package: docker"
  pip:
    name: docker

- name: "[app] | Build dockerapp containers"
  docker_container:
    name: "docker-app-{{ inventory_hostname | replace('.', '-') }}-{{ image.name | replace('/', '-') | replace('.', '-') | replace(':', '-') }}-{{ image_idx }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    image: "skn0tt/ansible-role-docker-app:v0.5.0"
    pull: true
    detach: false
    cleanup: true
    output_logs: true
    command: >
        {{ image.state | default('up') }} {{ image.name }}
        {% if image.config is defined %}
          {% for key, value in image.config.items() %}
            --set {{ key }}="{{ value }}"
          {% endfor %}
        {% endif %}
  register: dockerapp_containers
  loop: "{{ dockerapp_images }}"
  loop_control:
    loop_var: image
    index_var: image_idx
