---
# Prerequisites
- name: "Install python package: docker"
  pip:
    name: docker

# Pull Image
- name: Pull *.dockerapp Image
  docker_image:
    force: yes
    name: "{{ image }}"

# generate container name
- set_fact:
    container_name: "docker-app-{{ range(1, 10000) | random }}"

# Setup dockerapp
- name: Setup dockerapp
  docker_container:
    name: "{{ container_name }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: skn0tt/ansible-role-docker-app
    command: "{{ state }} {{ image }} {% for key, value in config.items() %} --set {{ key }}={{value}} {% endfor %}"

- name: Wait for container to stop
  command: "docker wait {{ container_name }}"

- name: Remove Container
  docker_container:
    name: "{{ container_name }}"
    state: absent
